begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public."User" (
  id integer generated by default as identity primary key,
  auth_user_id text unique,
  name text not null,
  user_id text not null unique,
  note text,
  mailadress text not null unique,
  icon_url text,
  plan_status text not null default 'free',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint user_name_length check (char_length(name) between 1 and 30),
  constraint user_note_length check (note is null or char_length(note) <= 120),
  constraint user_plan_status_not_blank check (char_length(trim(plan_status)) > 0)
);

create table if not exists public."Friend" (
  id integer generated by default as identity primary key,
  owner_user_id integer not null references public."User"(id) on delete cascade,
  friend_user_id integer not null references public."User"(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint friend_not_self check (owner_user_id <> friend_user_id)
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id integer not null references public."User"(id) on delete cascade,
  start_date date not null,
  end_date date,
  title text not null,
  start_time time,
  end_time time,
  category text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint events_title_not_blank check (char_length(trim(title)) > 0),
  constraint events_date_range_valid check (end_date is null or end_date >= start_date)
);

create table if not exists public.invites (
  id bigint generated by default as identity primary key,
  from_user_id integer not null references public."User"(id) on delete cascade,
  to_user_id integer not null references public."User"(id) on delete cascade,
  date date not null,
  message text not null,
  status text not null default 'request',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint invites_message_not_blank check (char_length(trim(message)) > 0),
  constraint invites_status_not_blank check (char_length(trim(status)) > 0),
  constraint invites_not_self check (from_user_id <> to_user_id)
);

create unique index if not exists user_auth_user_id_unique_idx
  on public."User" (auth_user_id)
  where auth_user_id is not null;

create unique index if not exists friend_owner_friend_unique
  on public."Friend" (owner_user_id, friend_user_id);

create index if not exists friend_owner_user_id_idx
  on public."Friend" (owner_user_id);

create index if not exists friend_friend_user_id_idx
  on public."Friend" (friend_user_id);

create index if not exists events_user_id_start_date_idx
  on public.events (user_id, start_date, start_time);

create index if not exists invites_to_user_id_created_at_idx
  on public.invites (to_user_id, created_at desc);

create index if not exists invites_from_user_id_created_at_idx
  on public.invites (from_user_id, created_at desc);

drop trigger if exists set_user_updated_at on public."User";
create trigger set_user_updated_at
before update on public."User"
for each row
execute function public.set_updated_at();

drop trigger if exists set_friend_updated_at on public."Friend";
create trigger set_friend_updated_at
before update on public."Friend"
for each row
execute function public.set_updated_at();

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at
before update on public.events
for each row
execute function public.set_updated_at();

drop trigger if exists set_invites_updated_at on public.invites;
create trigger set_invites_updated_at
before update on public.invites
for each row
execute function public.set_updated_at();

commit;
